name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: yarn build
        # Revert to netlify/actions/cli@master once https://github.com/netlify/actions/pull/23 is merged
      - uses: heizungsmacher/actions/cli@master
        with:
          args: deploy --dir=build/ --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
